### ISSUE TITLE
 too few arguments to function sapi_register_treat_data

### ISSUE THREAD

**Issue by willysr** [sektioneins/suhosin#16]
I just cloned the latest suhosin from git and tried to compile on PHP 5.4.3 and here's what i got
suhosin/treat_data.c:197:2: error: too few arguments to function ‘sapi_register_treat_data’
In file included from /home/willysr/suhosin/treat_data.c:30:0:
/usr/local/include/php/main/SAPI.h:197:14: note: declared here
make: **\* [treat_data.lo] Error 1

Slackware-Current
GCC 4.7.0
PHP 5.4.3
